[package]
name = "vsock"
version = "0.2.1"
authors = ["fsyncd"]
description = "Virtio socket support for Rust"
repository = "https://github.com/fsyncd/vsock-rs"
license = "Apache-2.0"
edition = "2018"
exclude = ["test_fixture"]

[dependencies]
libc = "0.2.79"
nix = "0.19.1"

[dev-dependencies]
rand = "0.8.3"
sha2 = ">=0.8.0"
