[package]
name = "echo_server"
version = "0.1.0"
authors = ["fsyncd"]
description = "Simple echo server for Virtio socket testing"
license = "Apache-2.0"
edition = "2018"

[dependencies]
clap = "2.33.3"
libc = "0.2.79"
nix = "0.19.0"
vsock = { path = "../" }
